// <auto-generated />
using System;
using Hatch.Api.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hatch.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927042212_PreApprovedIdentities")]
    partial class PreApprovedIdentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hatch.Api.Ef.EfAirQualitySample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("No2")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Ozone")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Pm10")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Pm25")
                        .HasColumnType("numeric");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsAqi")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Timestamp")
                        .IsUnique();

                    b.ToTable("AirQualitySamples");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfAuthGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CookieIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenIp")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AuthGrants");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfAuthInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBootstrap")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RedeemedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RedeemedGrantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("AuthInvites");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorOverride")
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderCalendarId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderColor")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ProviderCalendarId")
                        .IsUnique();

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendarAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccountEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("NeedsReauth")
                        .HasColumnType("boolean");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "AccountEmail")
                        .IsUnique();

                    b.ToTable("CalendarAccounts");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendarEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LocalEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LocalStartDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId", "ProviderEventId")
                        .IsUnique();

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCameraConnection", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiscoveredHost")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .HasColumnType("text");

                    b.Property<string>("PasswordProtected")
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("StreamPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.ToTable("CameraConnections");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ChannelId", "RequestedAt");

                    b.ToTable("Commands");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChosenActionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RunnerUpJson")
                        .HasColumnType("text");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("ControlDecisions");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExpectedState")
                        .HasColumnType("text");

                    b.Property<string>("ObservedState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SuppressedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("CommandId");

                    b.HasIndex("DeviceId", "SuppressedUntil");

                    b.ToTable("ControlOverrides");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("HaDeviceId")
                        .HasColumnType("text");

                    b.Property<int?>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDeviceChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableOptions")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("HaAttribute")
                        .HasColumnType("text");

                    b.Property<string>("HaEntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceChannels");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfEnvironmentReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DesiredTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsHeating")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EntityId", "Timestamp" }, "IX_EnvironmentReadings_EntityId_Timestamp")
                        .IsUnique();

                    b.ToTable("EnvironmentReadings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("Provider", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_ExternalIdentities_Provider_Email_Unclaimed")
                        .HasFilter("\"Subject\" IS NULL");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasFilter("\"Subject\" IS NOT NULL");

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfMeasurement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Timestamp" }, "IX_Measurements_ChannelId_Timestamp")
                        .IsUnique();

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfOAuthState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeVerifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReturnTo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("State")
                        .IsUnique();

                    b.ToTable("OAuthStates");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanelControlBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ItemId");

                    b.ToTable("PanelControlBindings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanelItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int?>("ControlKind")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<decimal?>("MaxF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinF")
                        .HasColumnType("numeric");

                    b.Property<string>("OnMode")
                        .HasColumnType("text");

                    b.Property<Guid>("PanelId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal?>("StepF")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PanelId");

                    b.HasIndex("RoutineId");

                    b.ToTable("PanelItems");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPersonPhoto", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PersonId");

                    b.ToTable("PersonPhotos");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsToggle")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutineAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RoutineId");

                    b.ToTable("RoutineActions");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfSiteSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SiteSettings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfStateChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Timestamp" }, "IX_StateChanges_ChannelId_Timestamp")
                        .IsUnique();

                    b.ToTable("StateChanges");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfWeatherAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AreaDescription")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Ends")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headline")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Onset")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderAlertId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Source", "ProviderAlertId")
                        .IsUnique();

                    b.ToTable("WeatherAlerts");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ComfortHighF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComfortLowF")
                        .HasColumnType("numeric");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfZoneConfig", b =>
                {
                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<decimal?>("ComfortHighF")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ComfortLowF")
                        .HasColumnType("numeric");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("EntityId");

                    b.ToTable("ZoneConfigs");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfAuthGrant", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfPerson", "Person")
                        .WithMany("Grants")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendar", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfCalendarAccount", "Account")
                        .WithMany("Calendars")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendarEvent", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfCalendar", "Calendar")
                        .WithMany("Events")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCameraConnection", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDevice", "Device")
                        .WithOne()
                        .HasForeignKey("Hatch.Api.Ef.EfCameraConnection", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCommand", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfControlDecision", "Decision")
                        .WithMany("Commands")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Decision");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlOverride", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfCommand", "Command")
                        .WithMany()
                        .HasForeignKey("CommandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Command");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDeviceChannel", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDevice", "Device")
                        .WithMany("Channels")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfExternalIdentity", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfPerson", "Person")
                        .WithMany("Identities")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfMeasurement", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanelControlBinding", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfPanelItem", "Item")
                        .WithMany("Bindings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanelItem", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfPanel", "Panel")
                        .WithMany("Items")
                        .HasForeignKey("PanelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfRoutine", "Routine")
                        .WithMany()
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Panel");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPersonPhoto", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfPerson", "Person")
                        .WithOne("Photo")
                        .HasForeignKey("Hatch.Api.Ef.EfPersonPhoto", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutineAction", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Ef.EfRoutine", "Routine")
                        .WithMany("Actions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfStateChange", b =>
                {
                    b.HasOne("Hatch.Api.Ef.EfDeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendar", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfCalendarAccount", b =>
                {
                    b.Navigation("Calendars");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfControlDecision", b =>
                {
                    b.Navigation("Commands");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfDevice", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPanelItem", b =>
                {
                    b.Navigation("Bindings");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfPerson", b =>
                {
                    b.Navigation("Grants");

                    b.Navigation("Identities");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Hatch.Api.Ef.EfRoutine", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
