// <auto-generated />
using System;
using Hatch.Api.Modules.Hatch;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hatch.Api.Modules.Hatch.Migrations
{
    [DbContext(typeof(HatchContext))]
    [Migration("20260928010000_PlaybookBranchStep")]
    partial class PlaybookBranchStep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hatch")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AnswersId")
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AnswersId");

                    b.HasIndex("IssueId", "CreatedAt");

                    b.ToTable("Comments", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AssigneeApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneePersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimChatter")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ClaimChatterAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ClaimHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimRunner")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DueAtHasTime")
                        .HasColumnType("boolean");

                    b.Property<string>("EffortOverride")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Expedited")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelOverride")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ReadyAtHasTime")
                        .HasColumnType("boolean");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId", "Number")
                        .IsUnique();

                    b.HasIndex("StatusId", "Rank");

                    b.ToTable("Issues", "hatch", t =>
                        {
                            t.HasCheckConstraint("CK_Issues_OneAssignee", "num_nonnulls(\"AssigneePersonId\", \"AssigneeApiKeyId\") <= 1");
                        });
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssueDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<long>("DependsOnId")
                        .HasColumnType("bigint");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnId");

                    b.HasIndex("IssueId", "DependsOnId")
                        .IsUnique();

                    b.ToTable("IssueDependencies", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssueEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IssueId", "At");

                    b.ToTable("IssueEvents", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchPlaybook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Effort")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("FromStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<int>("ToStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ToStatusId");

                    b.HasIndex("FromStatusId", "ToStatusId", "Types")
                        .IsUnique();

                    b.ToTable("Playbooks", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NextIssueNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Projects", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchProjectRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseBranch")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Canonical")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Remote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Canonical")
                        .IsUnique();

                    b.ToTable("ProjectRepositories", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchRunner", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<bool?>("Clones")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Line")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("LineAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxRuns")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxSpend")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Remotes")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Under")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UntilAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("Runners", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsDeferred")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Statuses", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchWorkLogEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostUsd")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Described")
                        .HasColumnType("boolean");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsError")
                        .HasColumnType("boolean");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("ModelUsage")
                        .HasColumnType("jsonb");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Turns")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IssueId", "EndedAt");

                    b.HasIndex("IssueId", "SessionId")
                        .IsUnique();

                    b.ToTable("WorkLogEntries", "hatch");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchComment", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchComment", "Answers")
                        .WithMany("AnsweredBy")
                        .HasForeignKey("AnswersId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answers");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssue", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchProject", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssueDependency", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "DependsOn")
                        .WithMany()
                        .HasForeignKey("DependsOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssueEvent", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "Issue")
                        .WithMany("Events")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchPlaybook", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchProjectRepository", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchProject", "Project")
                        .WithMany("Repositories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchWorkLogEntry", b =>
                {
                    b.HasOne("Hatch.Api.Modules.Hatch.EfHatchIssue", "Issue")
                        .WithMany("WorkLog")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchComment", b =>
                {
                    b.Navigation("AnsweredBy");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchIssue", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("Events");

                    b.Navigation("WorkLog");
                });

            modelBuilder.Entity("Hatch.Api.Modules.Hatch.EfHatchProject", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
